# cleanup
rm -rf obj_dir
rm -f blue_part.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace blue_part.sv --exe tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vblue_part.mk Vblue_part

# run executable simulation file
obj_dir/Vblue_part